name: 'GitHub Actions'
'on':
  - push
concurrency: 'ci-${{ github.ref }}'
env:
  APP_IMAGE: keboola-datadir-tests
  DOCKERHUB_USER: 'keboolabot'
  DOCKERHUB_TOKEN: '${{ secrets.DOCKERHUB_TOKEN }}'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        symfonyVersion: ["5.4.*", "6.4.*", "7.2.*"]
    steps:
      -
        name: 'Check out the repo'
        uses: actions/checkout@v2
      -
        name: 'Docker login'
        if: env.DOCKERHUB_TOKEN
        run: 'docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"'
      -
        name: 'Build image'
        run: 'docker build --build-arg SYMFONY_REQUIRE=${{ matrix.symfonyVersion }} -t $APP_IMAGE .'
      -
        name: 'Run tests'
        run: 'docker run ${{env.APP_IMAGE}} composer ci'
